# Generated by Django 3.1.4 on 2021-11-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulararaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veika_e_vakayacori', models.CharField(max_length=255)),
                ('gauna_vakayacori_kina', models.TextField(max_length=50)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '7. Bula Raraba',
            },
        ),
        migrations.CreateModel(
            name='Lewenilotu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaca_ni_vuvale', models.CharField(blank=True, max_length=255)),
                ('yaca_ni_vavakoso', models.CharField(blank=True, max_length=255, null=True)),
                ('tiki_ni_siganisucu', models.DateField(blank=True, max_length=255, null=True)),
                ('tagane_se_yalewa', models.CharField(blank=True, choices=[('Tgn', 'Tagane'), ('Ylw', 'Yalewa')], max_length=50)),
                ('tutu_vakalotu', models.CharField(blank=True, choices=[('sigadina', 'Siga Dina'), ('sigatuberi', 'Siga Tuberi'), ('lwnvks', 'Leweni Vavakoso')], max_length=50)),
                ('vakamacala_tale_eso', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': '1. Lewenilotu',
            },
        ),
        migrations.CreateModel(
            name='Valenilotu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valenilotu', models.CharField(max_length=255)),
                ('yaca_ni_vakatawa', models.CharField(blank=True, max_length=255)),
                ('vukevuke_ni_vakatawa', models.CharField(blank=True, max_length=255)),
                ('tuirara', models.CharField(blank=True, max_length=255)),
                ('vukevuke_ni_tuirara', models.CharField(blank=True, max_length=255)),
                ('vunivola', models.CharField(blank=True, max_length=255)),
                ('dauniyau', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_contact', models.CharField(blank=True, max_length=255)),
                ('vakamacala_tale_eso', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': '4. Valenilotu',
            },
        ),
        migrations.CreateModel(
            name='Veivakalotutaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yacani_program', models.CharField(max_length=255)),
                ('gauna_vakayacori_kina', models.TextField(max_length=50)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '6. Veivakalotutaki',
            },
        ),
        migrations.CreateModel(
            name='Veitosoyaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yacana', models.CharField(max_length=255)),
                ('toki', models.CharField(blank=True, choices=[('tm', 'Toki Mai'), ('ty', 'Toki Yani')], max_length=50)),
                ('siga_e_yaco_kina', models.DateField(max_length=50)),
                ('vola', models.FileField(blank=True, null=True, upload_to='documents/veitosoyaki/%Y/%m/%d/')),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
                ('lewenilotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.lewenilotu')),
            ],
            options={
                'verbose_name_plural': '5. Veitosoyaki',
            },
        ),
        migrations.CreateModel(
            name='Veitokani',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veitokani', models.CharField(max_length=255)),
                ('liuliu_ni_veitokani', models.CharField(blank=True, max_length=255)),
                ('vunivola_ni_veitokani', models.CharField(blank=True, max_length=255)),
                ('dauniyau_ni_veitokani', models.CharField(blank=True, max_length=255)),
                ('levu_ni_lavo_bula', models.CharField(blank=True, max_length=255)),
                ('veika_dau_qaravi', models.TextField(blank=True, max_length=255)),
                ('vakamacala_tale_eso', models.TextField(blank=True, max_length=255)),
                ('valenilotu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.valenilotu')),
            ],
            options={
                'verbose_name_plural': '3. Veitokani',
            },
        ),
        migrations.CreateModel(
            name='Matasiga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matasiga', models.CharField(max_length=255)),
                ('liuliu_ni_matasiga', models.CharField(blank=True, max_length=255)),
                ('vanua_dau_soqoni_kina', models.TextField(blank=True, max_length=255)),
                ('veika_dau_qaravi', models.TextField(blank=True, max_length=255)),
                ('vakamacala_tale_eso', models.TextField(blank=True, max_length=255)),
                ('valenilotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.valenilotu')),
            ],
            options={
                'verbose_name_plural': '2. Matasiga',
            },
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='lewe_ni_matasiga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.matasiga'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='lewe_ni_valenilotu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.valenilotu'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='lewe_ni_veitokani',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.veitokani'),
        ),
    ]
