# Generated by Django 3.2.13 on 2022-06-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0002_auto_20220628_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahublewenilotu',
            name='sega_ni_via_cula',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahublewenilotu',
            name='tabu_ni_cula',
            field=models.BooleanField(blank=True, default=0, help_text='Oqo ira na peipei lalai kei ira era vakatabui vakavuniwai me ra cula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datahublewenilotu',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Na nona tikini siga ni sucu - Dd/Mm/Yy eg 23/03/2010', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datahublewenilotu',
            name='date_papitaiso_kina',
            field=models.DateField(blank=True, help_text='Na tikini siga ka Papitaiso kina/ ke kilai ga na yabaki ia me vaka na 01/01/2002 e vakaraitaka ni yabaki 2002', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datahublewenilotu',
            name='date_sigadina_kina',
            field=models.DateField(blank=True, help_text='Na tikini siga ka Siga Dina kina/ ke kilai ga na yabaki ia me vaka na 01/01/2002 e vakaraitaka ni yabaki 2002', max_length=50, null=True),
        ),
    ]
